# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Check for updates daily
    # Target the 'canary' branch for all pull requests
    target-branch: "canary"
    # Specify reviewers for pull requests
    reviewers:
      - "pilot2254" # Main reviewer
      # - "another-reviewer"
    # Add a prefix to commit messages
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    # Group updates for certain packages if desired (optional)
    # groups:
    #   discordjs:
    #     patterns:
    #       - "discord.js"
    #   eslint:
    #     patterns:
    #       - "eslint"
    #       - "@typescript-eslint/*"
    # Limit the number of open PRs for version updates
    open-pull-requests-limit: 10
    # Automatically rebase PRs if they are rebaseable and pass CI
    rebase-strategy: "auto"
    # Specify labels for Dependabot PRs
    labels:
      - "dependencies"
      - "automated"
