// Collection of interesting facts
export const facts = [
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
  "A day on Venus is longer than a year on Venus. It takes 243 Earth days to rotate once on its axis, but only 225 Earth days to orbit the Sun.",
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly good to eat.",
  "The fingerprints of koalas are so similar to humans that they have on occasion been confused at crime scenes.",
  "Octopuses have three hearts, nine brains, and blue blood.",
  "Bananas are berries, but strawberries are not.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A group of flamingos is called a 'flamboyance'.",
  "Cows have best friends and get stressed when they are separated.",
  "The Great Wall of China is not visible from space with the naked eye, contrary to popular belief.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The Hawaiian alphabet has only 12 letters.",
  "A cockroach can live for several weeks without its head.",
  "Polar bears' fur is not white—it's actually transparent and reflects light.",
  "The world's oldest known living tree is over 5,000 years old.",
  "Humans share 50% of their DNA with bananas.",
  "The shortest commercial flight in the world takes just 1.7 minutes between the Scottish islands of Westray and Papa Westray.",
  "A day on Mercury lasts about 176 Earth days.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The average cloud weighs about 1.1 million pounds.",
  "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
  "The human nose can detect over 1 trillion different scents.",
  "The longest word without a vowel in the English language is 'rhythms'.",
  "The total weight of all the ants on Earth is roughly equal to the total weight of all the humans.",
  "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "The first oranges weren't orange—they were green.",
  "A group of unicorns is called a blessing.",
  "The shortest commercial flight in the world takes just 1.7 minutes between the Scottish islands of Westray and Papa Westray.",
  "The world's oldest known living tree is over 5,000 years old.",
  "Humans share 50% of their DNA with bananas.",
  "On August 10, 2018, Richard B. Russell, a 29-year-old Horizon Air ground service agent, shocked the world when he stole a Bombardier Q400 aircraft from Seattle-Tacoma International Airport. Despite no formal pilot training, Russell managed to perform an incredible barrel roll with the plane, a move so impressive that even experienced pilots called it remarkable, especially for such a large aircraft. The stunt, captured on video, amazed many and added to the surreal nature of the event. During the flight, Russell talked with air traffic control, showing moments of humor and honesty while also revealing his struggles. Tragically, the flight ended when he crashed the plane into Ketron Island, taking his own life. The incident left people amazed by his aerial skills but also raised concerns about mental health and aviation security. You can view the video here: https://www.instagram.com/p/DDzrMpVvJzh/",
]
